name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  PR_NUMBER: ${{ github.event.number }}



# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
  deploy-preview:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "PREVIEW_PATH=pr-preview/pr-${{ github.event.number }}" >> "$GITHUB_ENV"

      - uses: actions/setup-node@v4
      - name: Install Node Dependencies
        run: npm install

      - name: Install and Build
        if: github.event.action != 'closed' # Skip the build if the PR has been closed
        env:
          BASE: https://silver-couscous-4j3q154.pages.github.io/pr-preview/pr-${{ github.event.number }}
        run: npm run build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/